### PR TITLE
Make the group title be a stream selector on click, similar to Snapcast web

### LINKED ISSUE #37: Feature request: Quicker stream change via dropdown (like Snapweb) or buttons
I recently upgraded my system from an old version and discovered Snapweb for the first time; I am very impressed by it, particularly the ability to change the stream on a client or group with a drop-down menu; this makes it very quick and easy to select different "channels" per client.

I was hoping this feature would also be available in Snapdroid; currently, it takes four taps (gear, current stream, new stream, back) to change stream. So either a dropdown like Snapweb (two taps), or, even better, just a list of streams horizontally as radio buttons at the top, on the left of the gear, where the current stream name is, would make changing very quick.

I'm afraid my Java-foo is non-existent so I'm not sure how much help I could be coding this, but happy to give it a go is someone can point me in the right direction.

### PR DESCRIPTION
**Pull request by Zopieux**
Fixes #37.

Screenshot_1618183119

### CODE REVIEW

**Comment by Zopieux** [comment]
(the CI is broken btw, can't access dependencies)

**Comment by badaix** [comment]
Great, thanks! And Sorry for the delay.
I actually had already a similar implementation in my local git that is using a Spinner instead of an onClick listener, but the spinner had some different font and I didn't find the time to polish and finish this.

**Comment by badaix** [comment]
BTW: The CI should work now for PRs. There are some secrets involved for accessing the github hosted maven repo and for signing of the app. The dependencies are now downloaded and used from a local dir and the signing stuff will only run on push events, but not on pull_requests.

**Comment by Zopieux** [comment]
Great, thanks for the update!

**Pull request merged**
