### PR TITLE
Android TV app launcher

### PR DESCRIPTION
**Pull request by pmec**
Added the necessary changes to make app appear on the launcher.

### CODE REVIEW

**Comment by badaix** [comment]
Thanks! It seems that something is missing in the manifest:

```
2024-04-27T18:49:05.4747492Z   Lint found 2 errors, 76 warnings. First failure:
2024-04-27T18:49:05.4748251Z   
2024-04-27T18:49:05.4750112Z   /home/runner/work/snapdroid/snapdroid/Snapcast/src/main/AndroidManifest.xml:2: Error: Hardware feature android.hardware.touchscreen not explicitly marked as optional  [ImpliedTouchscreenHardware]
```

Can you please check? The failed action-run is [here](https://github.com/badaix/snapdroid/actions/runs/8859430425)

**Comment by pmec** [comment]
> Thanks! It seems that something is missing in the manifest:
> 
> ```
> 2024-04-27T18:49:05.4747492Z   Lint found 2 errors, 76 warnings. First failure:
> 2024-04-27T18:49:05.4748251Z   
> 2024-04-27T18:49:05.4750112Z   /home/runner/work/snapdroid/snapdroid/Snapcast/src/main/AndroidManifest.xml:2: Error: Hardware feature android.hardware.touchscreen not explicitly marked as optional  [ImpliedTouchscreenHardware]
> ```
> 
> Can you please check? The failed action-run is [here](https://github.com/badaix/snapdroid/actions/runs/8859430425)

Done.

**Comment by hllhll** [comment]
When a build for this is expected please :)

**Comment by badaix** [comment]
@hllhll I didn't test it yet, you can download and install the automated build: https://github.com/badaix/snapdroid/actions/runs/8908237942

**Pull request merged**
